# Generated by Django 5.0.2 on 2024-04-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='paypal_recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
