# Generated by Django 5.0.2 on 2024-03-10 10:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('short_title', models.CharField(max_length=25)),
                ('descriptions', models.CharField(max_length=100)),
                ('button', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sliders/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
