# Generated by Django 5.0.2 on 2024-03-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='status',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Sold')], default=True),
        ),
    ]
