# Generated by Django 5.0.2 on 2024-03-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_deliverycharge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverycharge',
            old_name='state',
            new_name='status',
        ),
    ]
