# Generated by Django 5.0.2 on 2024-04-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_notificationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmessage',
            name='hour_before',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
