# Generated by Django 5.0.2 on 2024-04-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_percentagegain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentagegain',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
