# Generated by Django 5.0.2 on 2024-03-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_messagedetails_recipientdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagedetails',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
