# Generated by Django 5.0.2 on 2024-03-31 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_alter_auction_expired_date'),
        ('messaging', '0004_messagedetails_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='auction_title',
        ),
        migrations.AddField(
            model_name='message',
            name='auction',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auctions.auction'),
        ),
    ]
