# Generated by Django 5.0.2 on 2024-04-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_remove_message_auction_title_message_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagedetails',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
