# Generated by Django 5.0.2 on 2024-04-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_message_read_messagedetails_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='read',
            new_name='recipient_read',
        ),
        migrations.AddField(
            model_name='message',
            name='sender_read',
            field=models.BooleanField(default=False),
        ),
    ]
