# Generated by Django 5.0.2 on 2024-04-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_rename_read_message_recipient_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender_read',
            field=models.BooleanField(default=True),
        ),
    ]
