# Generated by Django 5.0.2 on 2024-03-12 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_image1_auction_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='date_expired',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 9, 5, 10, 673614)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Deactive')], default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Deactive')], default=True),
        ),
    ]
