# Generated by Django 5.0.2 on 2024-03-20 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_latest_bid_alter_auction_date_expired_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='latest_bid',
            new_name='started_price',
        ),
        migrations.AddField(
            model_name='auction',
            name='amount_of_bids',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auction',
            name='date_expired',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 20, 34, 33, 648853)),
        ),
    ]
