# Generated by Django 5.0.2 on 2024-03-20 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_latest_bid_auction_started_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='bid_increments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auction',
            name='reserve_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='date_expired',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 20, 54, 50, 678159)),
        ),
    ]
