# Generated by Django 5.0.2 on 2024-03-21 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auction_bid_increments_auction_reserve_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='open_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auction',
            name='date_expired',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 28, 8, 53, 44, 241032)),
        ),
    ]
