# Generated by Django 5.0.2 on 2024-03-21 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auction_open_status_alter_auction_date_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder',
            name='open_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auction',
            name='date_expired',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 28, 11, 35, 31, 439054)),
        ),
    ]
