# Generated by Django 5.0.2 on 2024-03-21 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bidder_open_status_alter_auction_date_expired'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='date_created',
            new_name='started_date',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='date_expired',
        ),
        migrations.AddField(
            model_name='auction',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 28, 12, 2, 42, 812970)),
        ),
    ]
