# Generated by Django 5.0.2 on 2024-03-21 18:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_rename_date_created_auction_started_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidder',
            name='open_status',
        ),
        migrations.AlterField(
            model_name='auction',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 28, 18, 36, 10, 581533)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
