# Generated by Django 5.0.2 on 2024-03-21 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_bidder_open_status_alter_auction_expired_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 28, 19, 33, 37, 264723)),
        ),
    ]
