# Generated by Django 5.0.2 on 2024-03-26 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_auction_expired_date_billingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 2, 11, 25, 57, 524300)),
        ),
    ]
