# Generated by Django 5.0.2 on 2024-03-30 10:13

import auctions.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_alter_auction_expired_date_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 10, 13, 1, 459023)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=auctions.models.AutoIncrementNumberField(max_length=20, unique=True),
        ),
    ]
