# Generated by Django 5.0.2 on 2024-04-01 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_alter_auction_direct_buy_alter_auction_expired_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder',
            name='type',
            field=models.CharField(choices=[('auction', 'Auction'), ('buy-it-now', 'Buy-It-Now')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='auction',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 8, 23, 55, 29, 875960)),
        ),
    ]
