# Generated by Django 5.0.2 on 2024-04-02 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_bidder_type_alter_auction_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 9, 21, 22, 18, 586479)),
        ),
    ]
