# Generated by Django 5.0.2 on 2024-04-05 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_remove_transaction_auction_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='balance_type',
            field=models.CharField(blank=True, choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 17, 31, 48, 405460)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_type',
            field=models.CharField(blank=True, choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=20, null=True),
        ),
    ]
