# Generated by Django 5.0.2 on 2024-04-08 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0038_alter_auction_expired_date_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 15, 18, 18, 13, 837119)),
        ),
    ]
