# Generated by Django 5.0.2 on 2024-04-08 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0041_notification_created_at_notification_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auction',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 15, 19, 34, 44, 630494)),
        ),
    ]
