# Generated by Django 5.0.2 on 2024-04-09 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0043_transaction_author_alter_auction_expired_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 16, 18, 19, 32, 530355)),
        ),
    ]
