# Generated by Django 5.0.2 on 2024-04-23 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0045_alter_auction_expired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder',
            name='paid_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auction',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 18, 46, 24, 805833)),
        ),
    ]
