# Generated by Django 5.0.2 on 2024-04-25 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0047_alter_auction_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 8, 52, 24, 74667)),
        ),
    ]
